//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMICard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMICard()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int CardId { get; set; }
        public int UserId { get; set; }
        public int CardTypeId { get; set; }
        public string CardNumber { get; set; }
        public Nullable<decimal> UsedLimit { get; set; }
        public System.DateTime ValidTill { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public decimal CreditLimit { get; set; }
        public decimal AvailableLimit { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}
