//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMIPayment
    {
        public int PaymentId { get; set; }
        public int PurchaseId { get; set; }
        public decimal EMIAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentStatus { get; set; }
        public System.DateTime DueDate { get; set; }
        public int EMISequence { get; set; }
        public bool IsPaid { get; set; }
        public string PaymentMode { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
