//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Finance_Management_SystemEntities : DbContext
    {
        public Finance_Management_SystemEntities()
            : base("name=Finance_Management_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardType> CardTypes { get; set; }
        public virtual DbSet<EMICard> EMICards { get; set; }
        public virtual DbSet<EMIPayment> EMIPayments { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<UserBankDetail> UserBankDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<UserCardApplication> UserCardApplications { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<UserOtp> UserOtps { get; set; }
    }
}
