//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public decimal OrderAmount { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<int> EmiDuration { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
