//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.EMIPayments = new HashSet<EMIPayment>();
        }
    
        public int PurchaseId { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
        public int CardId { get; set; }
        public int EMIMonths { get; set; }
        public decimal TotalAmount { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PaymentMode { get; set; }
    
        public virtual EMICard EMICard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMIPayment> EMIPayments { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
