//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceManagementSystem_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCardApplication
    {
        public int ApplicationId { get; set; }
        public int UserId { get; set; }
        public int CardTypeId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AppliedOn { get; set; }
    
        public virtual CardType CardType { get; set; }
        public virtual User User { get; set; }
    }
}
